# Generated by Django 3.2.4 on 2021-06-20 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'поставщик',
                'verbose_name_plural': 'поставщики',
            },
        ),
        migrations.CreateModel(
            name='ProviderContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.PositiveSmallIntegerField(choices=[(1, 'телефон'), (2, 'почта')], default=1, verbose_name='Тип контакта')),
                ('contact', models.CharField(max_length=255, verbose_name='Контакт')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='providers.provider')),
            ],
            options={
                'verbose_name': 'контакт поставщика',
                'verbose_name_plural': 'контакты поставщика',
            },
        ),
        migrations.CreateModel(
            name='ProviderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='providers.provider')),
            ],
            options={
                'verbose_name': 'адрес поставщика',
                'verbose_name_plural': 'адреса поставщика',
            },
        ),
    ]
