# Generated by Django 3.2.4 on 2021-06-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.PositiveIntegerField(verbose_name='Закупочная стоимость'),
        ),
    ]
